### ISSUE TITLE
How do you get NPM installed for using in npm_mips_ar9331.sh ?

### ISSUE THREAD

**Issue by rjmackay** [nneves/openwrt_mips_ar9331_nodejs#1]
I've built v3 and node successfully using your script.. but I don't end up with a npm build.
Are you using a custom npm build for the npm_mips_ar9331.sh script? or just a standard x86 build?

**Comment by nneves** [comment]
Hi @rjmackay , my script will not cross compile the NPM module, I've seen other blogs with this done but found no instructions on how to do this, also the AR9331 MIPS SoC OpenWrt Linux module doesn't have the requirements to compile npm modules locally due to the lack of resources and GCC (it could pull standard pure Javascript modules, but would not run the ones that require node-gyp+gcc).

In order to cross-compile npm modules for the AR9331 OpenWrt platform I´ve made this script: https://github.com/nneves/openwrt_mips_ar9331_nodejs/blob/master/npm_mips_ar9331.sh

You should download this script into your cross-compile environment (previously set with the nodejs_v0.10.5_mips_ar9331.sh script), make it executable (chmod u+x) and the call it like this:

> ./npm_mips_ar9331.sh install serialport

This will use the npm from the cross-compile environment (X86 platform, so you will need to install node.js on your cross-compile env., if possible use a similar version) to get the npm module source and if it requires to cross-compile it will know on how to call node-gyp with the correct exported OpenWrt G++/GCC/etc.

This will generate a node_modules directory will the required module, you will need to make a TAR from this and send it to the AR9331 board via scp (or with a USB Flash drive).

Hope this helps, it's sort of manual procedure and not easy, but it gets things done, at least for me.

**Comment by rjmackay** [comment]
Thanks.
I managed to build the npm modules.

I installed nodejs (and npm) from a ppa

```
apt-get install python-software-properties
apt-add-repository ppa:chris-lea/node.js
apt-get update
apt-get install nodejs
```

Checked out the node app I was building and ran
`./npm_mips_ar9331.sh install`
from within the project to install everything in package.json

All seemed to go ok. Sadly in the end I think the app was too memory/cpu heavy to run on my little WR703N

**Comment by nneves** [comment]
The WR703N is already running to the limit and barely runs node.js, normally I use this flags to run the node.js app:

```
node --stack_size=1024 --max_old_space_size=20 --max_new_space_size=2048 --max_executable_size=5 --gc_global --gc_interval=100 app.js
```

Nevertheless, RAM usage will be close to 100%, not easy to get some additional extra. You could use other AR9331 SoC boards such as Arduino YUN or Carambola2, both have double RAM space and more FLASH available, node.js binary and NPM packages will be compatible with the OpenWrt running on theses boards!
